- name: Deploy Infraestructure with terraform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ./infra

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: ./infra
    - name: Get Terraform output
      command: terraform output -json
      args:
        chdir: ./infra
      register: terraform_output