---
-
  hosts: 
  gather_facts: true

  tasks:
  #-----------------------
  #Obtener outputs de terraform
  #-------------------------
    - name: obtener los oututs de terraform
      command: terraform output -json
      args: 
        chdir: "./infra"
      register: tf_output_raw
  
    
    - name: Mostrar la IP pública
      debug:
         var: tf_output_raw



#-----------------------
#set de variables 
#-------------------------
    
    - name: Parsear los outputs de terraform
      set_fact:
        acr_server: "{{ (tf_outputs.stdout | from_json).acr_login_server.value }}"
        acr_username: "{{ (tf_outputs.stdout | from_json).acr_username.value }}"
        acr_password: "{{ (tf_outputs.stdout | from_json).acr_password.value }}"

#-----------------------
#Login en ACR
#-------------------------
    - name: Login en ACR
      containers.podman.podman_login:
        registry_url: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

#-----------------------
#descargar la imagen del acr
#-------------------------
    - name: Descargar la imagen del ACR
      containers.podman.podman_image:
        name: "{{ acr_login_server }}/myapp:latest"
        pull: true

#-----------------------
#Ejecutar la imagen en el servidor web
#-------------------------
    - name: Ejecutar la imagen en el servidor web
      containers.podman.podman_container:
        name: myapp_container
        image: "{{ acr_login_server }}/myapp:latest"
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"